from django.urls import path  
from myapp import views  
urlpatterns = [  
    path('admina',views.admina),
    path('adminhome',views.adminhome),
    path('addcar',views.add_car),
    path('',views.home),
    path('showcar',views.showcars),
    path('edit/<int:id>',views.edit),
    path('staff',views.staff),
    path('log/<int:token>',views.logins),
    path('register',views.register),
    path('userhome',views.register),
    path('profile',views.profile),
    path('editprofile',views.editprofile),
    path('cars',views.carsdef),
    path('booknow/<int:id>',views.booknow),
    path('booking/<int:id>',views.booking),
    path('logout',views.logout_view),
    path('orders',views.corder),
    path('deleted/<int:j>',views.deleted),
    path('bookings',views.orders),
    path('reasondelete/<int:id>',views.delreason),
    path('dlog/<int:id>',views.dlog),
    path('changepass',views.changepass),
    path('resetpass',views.passreset),
    path('feedbac',views.feedbak),
    path('feedback',views.stffeedback),
]  