# Generated by Django 4.1.7 on 2023-06-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rentedcar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.car_details'),
        ),
    ]
