# Generated by Django 4.1.7 on 2023-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_rentedcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_details',
            name='d_time',
        ),
        migrations.AlterField(
            model_name='car_details',
            name='d_place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
