# Generated by Django 4.1.7 on 2023-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_car_details_d_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryandreturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('dplace', models.CharField(max_length=100)),
                ('rplace', models.CharField(max_length=100)),
                ('rcarid', models.IntegerField()),
            ],
        ),
    ]
