# Generated by Django 4.1.7 on 2023-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_deliveryandreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryandreturn',
            name='fdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryandreturn',
            name='license',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryandreturn',
            name='rdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryandreturn',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryandreturn',
            name='dplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryandreturn',
            name='rcarid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveryandreturn',
            name='rplace',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
